fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,33 +1,52 @@
 version: 2.1
 
-commands:
-  destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
- 
-    steps:
-      - run:
-          name: Destroy environments
-          when: on_fail
-          command: |
-            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
-            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
-            exit 1
+orbs:
+  aws-cli: circleci/aws-cli@3.1.5
+  python: circleci/python@2.1.1
+# commands:
+#   destroy-environment:
+#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+#     parameters:
+#       # CIRCLE_WORKFLOW_ID:
+#       #   type: string
+#       #   required: true
+#     steps:
+#       - run:
+#           name: destroy_environments
+#           when: on_fail
+#           command: |
+#              # Use the AWS CLI to delete the CloudFormation stacks
+#             aws cloudformation delete-stack --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}"
+#             aws cloudformation delete-stack --stack-name "udapeople-front-end-${CIRCLE_WORKFLOW_ID}"
+#             exit 1
 
-  revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.  
-    steps:
-      - run:
-          name: Revert migrations
-          when: on_success
-          command: |
-            SUCCESS=$(curl -H "token: 817f662a-e732-4a62-87ae-19e812bb83ce" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
-            if (( $SUCCESS == 1 ));
-            then
-            cd ~/project/backend
-            npm install
-            npm run migration:revert
-            fi 
-            
+#   revert-migrations:
+#     description: Revert the last migration if successfully run in the current workflow.
+#     parameters:
+#       CIRCLE_WORKFLOW_ID:
+#         type: string
+#         required: true
+#       success_url:
+#         type: string
+#         required: true
+#     steps:
+#       - run:
+#           name: "Revert-migrations"
+#           when: on_fail
+#           command: |
+#             # Check if there was a successful migration
+#             curl -s $success_url | grep -q success
+#             if [[ $? == 0 ]]; then
+#               # Revert the migration
+#               cd ~/project/backend
+#               npm install
+#               # Add revert code here. You can find this in the Getting Started section.
+#               exit 1
+#             else
+#               # No need to revert the migration
+#               exit 0
+#             fi
+
 jobs:
   build-frontend:
     docker:
@@ -37,11 +56,11 @@ jobs:
       - restore_cache:
           keys: [frontend-build]
       - run:
-          name: Build front-end
+          name: "Build-front-end"
           command: |
-            cd frontend
-            npm install
-            npm run build
+             cd frontend
+             npm i
+             npm run build
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -54,11 +73,11 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: Back-end build
+          name: "Back-end-build"
           command: |
-            cd backend
-            npm install
-            npm run build
+             cd backend
+             npm i
+             npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -69,27 +88,26 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-test]
+          keys: [frontend-build]
       - run:
-          name: Run front-end test
-          command: |
-            cd frontend
-            npm install
-            npm run test
-                
+         name: "Run-frontend-test"
+         command: |
+             cd frontend
+             npm install
+             npm run test
   test-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-test]
+          keys: [backend-build]
       - run:
-          name: Run backend-end test
+          name: "Run-Back-end-test"
           command: |
-            cd backend
-            npm install
-            npm run test
+             cd backend
+             npm install
+             npm run test
 
   scan-frontend:
     docker:
@@ -97,15 +115,16 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-scan]
+          keys: [frontend-build]
       - run:
-          name: Run frontend-end scan
-          command: |
+         name: "Run-frontend-scan"
+         command: |
             cd frontend
             npm install
             npm audit fix --audit-level=critical --force
             npm audit fix --force
             npm audit --audit-level=critical
+             
 
   scan-backend:
     docker:
@@ -113,206 +132,188 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-scan]
+          keys: [backend-build]
       - run:
-          name: Run backend-end scan
+          name: "Run-Back-end-scan"
           command: |
             cd backend
             npm install
             npm audit fix --audit-level=critical --force
             npm audit fix --force
             npm audit --audit-level=critical
+             
 
-  deploy-infrastructure:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install Dependencies
-          command: |
-            cat .circleci/ansible/inventory.txt
-            ls ~/project/.circleci/ansible/
-            cat ~/project/.circleci/ansible/inventory.txt
-            yum -y install tar gzip jq npm
+  # deploy-infrastructure:
+  #   docker:
+  #     #- image: circleci/node:13.8.0 that supports AWS CLI
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: "Ensure-back-end-infrastructure-exists"
+  #         command: |
+  #           aws cloudformation deploy \
+  #             #--template-file .circleci/files/backend.yml \
+  #             #--tags project=udapeople \
+  #             #--stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"  \
+  #             #--parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+  #             exit 1
+  #     - run:
+  #         name: "Ensure-front-end-infrastructure-exist"
+  #         command: |
+  #           aws cloudformation deploy \
+  #             #--template-file .circleci/files/frontend.yml \
+  #             #--tags project=udapeople \
+  #             #--stack-name "udapeople-front-end-${CIRCLE_WORKFLOW_ID:0:8}"" \
+  #             #--parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}"  
+  #             exit 1
+  #     - run:
+  #         name: "Add-back-end-ip-to-ansible-inventory"
+  #         command: |
+  #           # Fetch the public IP of the EC2 instance
+  #           EC2_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=your-instance-name" --query "Reservations[].Instances[].PublicIpAddress" --output text)
 
-      - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-              --tags project=udapeople
+  #           # Append the IP to the inventory.txt file
+  #           echo "your-instance-name ansible_host=$EC2_PUBLIC_IP ansible_user=ubuntu" >> .circleci/ansible/inventory.txt
 
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-              --tags project=udapeople
+  #           # Persist the modified inventory file to the workspace
+  #           cp .circleci/ansible/inventory.txt $HOME/workspace/inventory.txt
+  #           exit 1
+  #     - persist_to_workspace:
+  #         root: ~/
+  #         paths:
+  #           - project/.circleci/ansible/inventory.txt
+  #     # Here's where you will add some code to rollback on failure      
 
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
-            echo [all] > inventory
-            aws ec2 describe-instances \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --filters "Name=tag:project,Values=udacity" \
-            --output text >> .circleci/ansible/inventory.txt
+  # configure-infrastructure:
+  #   docker:
+  #    # - image: circleci/node:13.8.0 that supports Ansible
+  #   steps:
+  #     - checkout
+  #     # Add ssh keys with fingerprint
+  #     # attach workspace
+  #     - run:
+  #         name: "Install-dependencies"
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  #     - run:
+  #         name: "Configure-server"
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  #     # Here's where you will add some code to rollback on failure      
 
-      - persist_to_workspace:
-          root: .circleci/
-          paths:
-            - ansible/inventory.txt
-      - destroy-environment
-
-  configure-infrastructure:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints: ["74:3b:e5:07:2a:de:b4:4c:c5:c0:5d:c8:b9:45:d9:b8"]
-      - attach_workspace:
-          at: /tmp/ansible
-      - run:
-          name: Install Dependecies
-          command: |
-            apk add openssh-client
-            apk add --update ansible
-      - run:
-          name: Configure server
-          command: |
-            ansible-playbook -i /tmp/ansible/inventory.txt .circleci/ansible/configure-server.yml
-      - destroy-environment
-
-  run-migrations:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - run:
-          name: Run migrations
-          command: |
-            cd backend
-            npm install
-            npm run migrations > migrations_dump.txt
-      - run:
-          name: Send migration results to memstash
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
-            fi
-      - destroy-environment
+  # run-migrations:
+  #   docker:
+  #    # - image: circleci/node:13.8.0 that supports NodeJS
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: "Run-migrations"
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  #     - run:
+  #         name: "Send-migration-results-to-memstash"
+  #         command: |
+  #           # Your code here
+  #           exit 1
+  #    # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
-      - image: amazon/aws-cli
+     - image: circleci/node:13.8.0 that supports AWS CLI
     steps:
       - checkout
       - run:
-          name: Install tar/gzip utility
+          name: "Install-dependencies"
           command: |
-            yum -y install tar
-            yum -y install gzip
+            # your code here
       - run:
-          name: Install dependencies
+          name: "Get-backend-url"
           command: |
-            sudo apt-get update && sudo apt-get install -yy less
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-      - run:
-          name: Get backend url
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances...............)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      - destroy-environment
-                    
-  deploy-backend:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints: ["74:3b:e5:07:2a:de:b4:4c:c5:c0:5d:c8:b9:45:d9:b8"]
-      - attach_workspace:
-          at: .
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update ansible curl rsync openssh nodejs npm
-            ansible --version
-            pip install awscli
-            aws --version
-      - run:
-          name: Deploy backend
-          command: |
-            cd backend
-            npm i
-            npm run build
-            cd ..
-            tar -C backend -czvf artifact.tar.gz .
-            cd .circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
-      - destroy-environment  
-
-  smoke-test:
-    docker:
-      - image: python:3.7-alpine3.11 
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update curl nodejs npm
-            pip install awscli
-      - run:
-          name: Get backend url
-          command: |
+            # your code here
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-                return 0
-            else
-                return 1
-            fi
       - run:
-          name: Backend smoke test.
+          name: "Deploy-frontend-objects"
           command: |
-            export BACKEND_URL=$(curl -H "token: 817f662a-e732-4a62-87ae-19e812bb83ce" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
-            curl "$BACKEND_URL/api/status"
-      - run:
-          name: Frontend smoke test.
-          command: |
-             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-             echo ${URL} 
-             if curl -s ${URL} | grep "Welcome"
-             then
-                 return 1
-             else
-                 return 1
-             fi
-      - destroy-environment 
+            # your code here
+      # Here's where you will add some code to rollback on failure      
 
+  deploy-backend:
+    docker:
+     - image: circleci/node:13.8.0 that supports Ansible
+    steps:
+      - checkout
+      # Add ssh keys with fingerprint
+      # attach workspace
+      - run:
+          name: "Install-dependencies"
+          command: |
+            # your code here
+      - run:
+          name: "Deploy-backend"
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure  
+
+  # smoke-test:
+  #   docker:
+  #     # Lightweight Docker image 
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: "Install-dependencies"
+  #         command: |
+  #           # your code here
+  #     - run:
+  #         name: "Get-backend-url"
+  #         command: |
+  #           # your code here
+  #     - run:
+  #         name: "Backend-smoke-test."
+  #         command: |
+  #           # your code here
+  #     - run:
+  #         name: "Frontend-smoke-test."
+  #         command: |
+  #           # your code here
+  #     # Here's where you will add some code to rollback on failure  
+ 
+  # cloudfront-update:
+  #   docker:
+  #   #  - image: circleci/node:13.8.0 that supports AWS CLI
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: "Install-dependencies"
+  #         command: |
+  #           # your code here
+  #     - run:
+  #         name: "Update-cloudfront-distribution"
+  #         command: |
+  #           # your code here
+  #     # Here's where you will add some code to rollback on failure  
+
+cleanup:
+    docker:
+    #  - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: "Get-old-stack-workflow-id"
+          command: |
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: "Remove-old-stacks-and-files"
+          command: |
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              # your code here
+            fi
 
 workflows:
   default:
@@ -327,18 +328,22 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [master]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]                                      
+      # - deploy-infrastructure:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #     filters:
+      #       branches:
+      #         only: [test-feature-branch]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
